spring:
  config:
    import: file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL}
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  flyway:
    baseline-on-migrate: true
  security:
    jwt:
      secret: ${JWT_SECRET}
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLI_ID}
            client-secret: ${GOOGLE_CLI_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: openid,email,profile
aws:
  access: ${AWS_ACCESS}
  secret: ${AWS_SECRET}
